### PR TITLE
Wip

### PR DESCRIPTION
**Pull request by nrgaway**

### CODE REVIEW

**Comment by nrgaway** [comment]
This version relies on the `core-agent-linux` changes.

The upstream version tag '9.6.6' is not yet in place.  Patrick will need to review changes and sign.

Whonix '10.0.1' branch is also available which will supersede this branch.

Basic testing on Whonix 10 has been completed with everything seeming to work as expected and am just waiting for Patrick to release the official version tag as well as tag `qubes-whonix`

**Comment by nrgaway** [comment]
I have an issue with workstation.  stay tuned for fix

**Comment by nrgaway** [comment]
Workstation fixed; best to wait for Patrick to sign tags so I can repo reference to my personal repo

**Comment by nrgaway** [comment]
It's finally complete!  Included is an update to Whonix `9.6.2` (tagged as `v9.6.9`) and Whonix `10`, tagged as `v10.0.5`.  Existing Whonix templates will also be able to update manually via `apt-get`

When Whonix was moved into its own package here, it was at version `9.6.2` (master branch).  I had then created 3 more branches being Whonix9, Whonix10, and Whonix11.  All work was done it specific branches, cherry-picking between them until they were all complete.  Once the branches were complete and tested I merged:
  - Whonix9 into master; tagged as v9.8.9
  - Whonix10 into master; tagged as v10.0.5
  - master into this `wip` branch since it contained the initial PR

Although Whonix11 builds, it will not be merged until upstream is released.  I will leave my upstream branches in my repo as I not sure how you want to handle all the versions.  As you will notice, `v9.6.9` will be skipped in favor of `v10.0.5` although I did spend time to test that build as well.

Major release notes:
- Upgrade to Whonix 10
- Appmenus moved from `builder-debian`
- whonix.conf fixed and builds (currently needs repo override until it in main repo)
- README.whonix updated
- `template-whonix` will download its own source files, saving the need to run `get-sources` twice

`builder-debian` and `qubes-builder` also have `Whonix` related changes of which I will submit PR next

**Comment by nrgaway** [comment]
and `linux-template-builder`

**Comment by marmarek** [comment]
I have two problems with this:
1. `logname` does not work when no controlling tty is available - this is the case when building in DispVM (fixed in branch `fixes` in my repo)
2. build hangs in 1100_prepare-build-machine, when it tries to install **and start** acpid. Shouldn't `invoke-rc.d` be disabled during build process?

**Comment by nrgaway** [comment]
On 9 May 2015 at 06:11, Marek Marczykowski-Górecki <notifications@github.com
> wrote:

> I have two problems with this:
> 1. logname does not work when no controlling tty is available - this is
> the case when building in DispVM (fixed in branch fixes in my repo)
> 2. build hangs in 1100_prepare-build-machine, when it tries to install *and
> start* acpid. Shouldn't invoke-rc.d be disabled during build process?
>
Interesting.  I don't experience the hang myself, but invoke-rc.d never
needed to really be disabled since we install systemd and systemd prevents
services from starting in chroot environment.

I changed the installation order of installing Whonix 10 (Its installed
before any other packages now) since it is really fussy on already
installed applications and found it a more reliable install when Whonix is
being installed first. I know Patrick has code to prevent application
startup as well.

I have created a new branch in builder_debian called 'policy-rc' in my
repos that implements (creates) a policy-rc.d file which returns an exit
return value of 101. invoke-rc.d should call policy-rc.d and then prevent
service startup.

I have not tested that commit since I'm in middle of build and I will be
heading off to sleep soon, but will do it later, but I push the change to
my repo if you wanted to try it in mean time

**Comment by nrgaway** [comment]
I just did a quick test with those changes on a wheezy template and the `poliy-rc.d` addition seems to be preventing startup of services since I had to reboot and repair system ;)

**Pull request merged**
